# Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris

In [3]:
!pip install tensorflow

# Import Dependencies

In [ ]:
from tensorflow.keras.layers import Dense #NN

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

In [6]:
# 0 - [1, 0, 0]
# 1 - [0, 1, 0]
# 2 - [0, 0, 1]

In [7]:
data = load_iris()
features = data['data']
target = data['target']

In [8]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
targets_ = to_categorical(target, num_classes=3)

In [10]:
features.shape[1]

4

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, targets_)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train)

# Build and Compile Model

In [12]:
model = Sequential()

model.add(Dense(100, input_shape=(features.shape[1],)))
model.add(Dense(30, activation="relu"))
# model.add(Dense(45, activation="relu"))
# model.add(Dense(32, activation="relu"))
# model.add(Dense(23, activation="relu"))
model.add(Dense(3, activation="softmax"))

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               500       
                                                                 
 dense_1 (Dense)             (None, 30)                3030      
                                                                 
 dense_2 (Dense)             (None, 3)                 93        
                                                                 
Total params: 3,623
Trainable params: 3,623
Non-trainable params: 0
_________________________________________________________________


# Fit,Predict and Evaluate

In [14]:
import tensorflow

model.compile(optimizer="sgd", 
              loss=tensorflow.keras.losses.CategoricalCrossentropy(), 
              metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train, epochs=50, validation_data=(X_val, y_val))

Epoch 1/50
3/3 [==============================] - 1s 86ms/step - loss: 1.2284 - accuracy: 0.5595 - val_loss: 0.9329 - val_accuracy: 0.5714
Epoch 2/50
3/3 [==============================] - 0s 12ms/step - loss: 0.7900 - accuracy: 0.7381 - val_loss: 0.8279 - val_accuracy: 0.5714
Epoch 3/50
3/3 [==============================] - 0s 6ms/step - loss: 0.6978 - accuracy: 0.7381 - val_loss: 0.9750 - val_accuracy: 0.5714
Epoch 4/50
3/3 [==============================] - 0s 12ms/step - loss: 0.6744 - accuracy: 0.7381 - val_loss: 0.8480 - val_accuracy: 0.5714
Epoch 5/50
3/3 [==============================] - 0s 12ms/step - loss: 0.6374 - accuracy: 0.7381 - val_loss: 0.7301 - val_accuracy: 0.5714
Epoch 6/50
3/3 [==============================] - 0s 12ms/step - loss: 0.6138 - accuracy: 0.7619 - val_loss: 0.8690 - val_accuracy: 0.5714
Epoch 7/50
3/3 [==============================] - 0s 15ms/step - loss: 0.5763 - accuracy: 0.7381 - val_loss: 0.7044 - val_accuracy: 0.5714
Epoch 8/50
3/3 [============

In [16]:
X_train.shape

(84, 4)

In [17]:
y_train.shape

(84, 3)

In [18]:
#y_pred = model.predict(X_test)
y_pred = np.argmax(model.predict(X_test),axis=1)

2/2 [==============================] - 0s 0s/step


In [19]:
y_pred

array([1, 1, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2,
       0, 1, 2, 0, 1, 1, 1, 2, 2, 1, 0, 2, 0, 1, 0, 0], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score

y_test_ = []

for i in y_test:
    
    y_test_.append(np.argmax(i))

accuracy_score(y_test_, y_pred)

0.9473684210526315

# Saving and Reloading

In [21]:
model.save("NN.h5")

In [22]:
from tensorflow.keras.models import load_model

In [23]:
model = load_model("./NN.h5")

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               500       
                                                                 
 dense_1 (Dense)             (None, 30)                3030      
                                                                 
 dense_2 (Dense)             (None, 3)                 93        
                                                                 
Total params: 3,623
Trainable params: 3,623
Non-trainable params: 0
_________________________________________________________________


In [25]:
clas = model.predict([[0.9, 0.8, 0.5, 0.9]])

1/1 [==============================] - 0s 48ms/step


In [26]:
clas

array([[0.28534973, 0.3422799 , 0.3723703 ]], dtype=float32)

In [27]:
# np.argmax(clas)

In [28]:
classes = ['iris satosa', 'virginica', 'iris color']

classes[np.argmax(clas)]

'iris color'